###############################################
### Config Explanation
###############################################
# Settings:
#   Item:
#     Material --> If a player right clicks that block in the inventory the HatGUI will open
#     Data-Value --> Data value of the item.... Works like "WOOL:14" but without the "WOOL:" [This can be removed if you dont want a data value]
#     Name --> Custom Item Name
#     Lore --> Add lore to item [this can be removed if you dont want lore]
#     Glow --> Does the Hats GUI Item glow ? True = yes... False = no.
#   Give-On-Login --> If true and a player with "Hats.Use" logs in we give them the block. If false everyone gets the item on login. [still requires perms to use it though]
# GUI:
#   Name --> Name of the GUI... Appears in the top left of the menu
#   Rows --> Every row counts as 9 slots.
# Items:
#   <anything_here>:
#     Slot --> Slot to place the item (In Hats GUI the slots do not start at 0... So count slots from left to right starting at 1)
#     Name --> Name of the Item
#     Material --> What item should be in the Slot
#     Lore --> Should the item have lore? remove this if you dont want lore on your item.

Settings:
  Item:
    Material: WOOL
    Data-Value: 14
    Name: "Hats GUI"
    Lore: "Select your hat with a beautiful GUI"
    Glow: true
  Give-On-Login: true
GUI:
  Name: "Hats GUI"
  Rows: 3
Items:
  grass_hat:
    Slot: 11
    Name: "Grass Hat"
    Material: GRASS
    Lore:
      - "Get a grass hat!"
  diamond_hat:
    Slot: 11
    Name: "Diamond Hat"
    Material: DIAMOND_BLOCK
    Lore:
      - "Be the envy of all your friends"
  Walking_Lanter:
    Slot: 11
    Name: "Have a light source wherever you go!"
    Material: GLOWSTONE
    Lore:
      - "Become a light!"
      - "And rule the night!"
  obsidian:
    Slot: 11
    Name: "Indestructile Head"
    Material: OBSIDIAN
  